a=int(input("enter a value:"))
b=int(input("enter b value :"))
print("add =",a+b)
print("sub=",a-b)
print("mul=",a*b)
print("div=",a/b)
print("floor div",a//b)
print("mode",a%b)
print("power",a**b)
print(f"the sum of {a} and {b}",a+b)
